/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fix;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projekuasstrukdat.Barang;
import projekuasstrukdat.Inventory;

/**
 *
 * @author HP
 */
public class Menu extends javax.swing.JFrame {

    Inventory inv = new Inventory(100);
    private DefaultTableModel tabmode;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        pan_barangKeluar.setVisible(false);
        pan_barangMasuk.setVisible(false);
        pan_tampilkanBarang.setVisible(false);
    }

    public void display() {
        tabmode = (DefaultTableModel) jTable1.getModel();
        tabmode.setRowCount(0);
        jTable1.setModel(tabmode);
        Barang[] datas = inv.getAllSortedBarang(); // Dapatkan data yang telah diurutkan
        for (Barang barang : datas) {
            Object[] row = new Object[4];
            row[0] = barang.getIdBarang();
            row[1] = barang.getNamaBarang();
            row[2] = barang.getTanggalMasuk();
            row[3] = barang.getJumlahBarang();
            tabmode.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pan_tampilkanBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pan_barangKeluar = new javax.swing.JPanel();
        isikm1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Kode_Barang4 = new javax.swing.JTextField();
        Kode_Barang5 = new javax.swing.JTextField();
        btnok1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        pan_barangMasuk = new javax.swing.JPanel();
        isikm = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Kode_Barang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Kode_Barang1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Kode_Barang2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Kode_Barang3 = new javax.swing.JTextField();
        btnok = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setText("BARANG MASUK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 168, 71));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setText("BARANG KELUAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 168, 71));

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setText("TAMPILKAN BARANG");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 168, 71));

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setText("KEMBALI");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 168, 71));

        pan_tampilkanBarang.setPreferredSize(new java.awt.Dimension(500, 360));
        pan_tampilkanBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("DATA BARANG TOKO ");
        pan_tampilkanBarang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Barang", "Nama Barang", "Tanggal Masuk", "Jumlah Barang"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pan_tampilkanBarang.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 253));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        pan_tampilkanBarang.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 80, 310, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Cari Nama Barang");
        pan_tampilkanBarang.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINDOWS 10\\Downloads\\backgroudmenu.jfif")); // NOI18N
        pan_tampilkanBarang.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        getContentPane().add(pan_tampilkanBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 500, 400));

        pan_barangKeluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isikm1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        isikm1.setText("BARANG KELUAR");
        pan_barangKeluar.add(isikm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 220, 48));

        jLabel5.setText("Kode Barang");
        pan_barangKeluar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel7.setText("Jumlah Barang");
        pan_barangKeluar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        Kode_Barang4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kode_Barang4ActionPerformed(evt);
            }
        });
        pan_barangKeluar.add(Kode_Barang4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 328, 30));

        Kode_Barang5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kode_Barang5ActionPerformed(evt);
            }
        });
        pan_barangKeluar.add(Kode_Barang5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 328, 30));

        btnok1.setBackground(new java.awt.Color(204, 204, 204));
        btnok1.setText("OK");
        btnok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnok1ActionPerformed(evt);
            }
        });
        pan_barangKeluar.add(btnok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 133, 39));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINDOWS 10\\Downloads\\backgroudmenu.jfif")); // NOI18N
        pan_barangKeluar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        getContentPane().add(pan_barangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 500, 400));

        pan_barangMasuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isikm.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        isikm.setText("BARANG MASUK");
        pan_barangMasuk.add(isikm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 200, 48));

        jLabel2.setText("Kode Barang");
        pan_barangMasuk.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        Kode_Barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kode_BarangActionPerformed(evt);
            }
        });
        pan_barangMasuk.add(Kode_Barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 310, 30));

        jLabel3.setText("Nama Barang");
        pan_barangMasuk.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        Kode_Barang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kode_Barang1ActionPerformed(evt);
            }
        });
        pan_barangMasuk.add(Kode_Barang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 310, 30));

        jLabel4.setText("Tanggal Masuk");
        pan_barangMasuk.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        Kode_Barang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kode_Barang2ActionPerformed(evt);
            }
        });
        pan_barangMasuk.add(Kode_Barang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 310, 30));

        jLabel6.setText("Jumlah Barang");
        pan_barangMasuk.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        Kode_Barang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kode_Barang3ActionPerformed(evt);
            }
        });
        pan_barangMasuk.add(Kode_Barang3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 310, 30));

        btnok.setBackground(new java.awt.Color(204, 204, 204));
        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });
        pan_barangMasuk.add(btnok, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 133, 39));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINDOWS 10\\Downloads\\backgroudmenu.jfif")); // NOI18N
        pan_barangMasuk.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        getContentPane().add(pan_barangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 500, 400));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("SELAMAT DATANG");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINDOWS 10\\Downloads\\bgcolom.jfif")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 300, 380));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINDOWS 10\\Downloads\\bgcolom.jfif")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pan_barangKeluar.setVisible(false);
        pan_barangMasuk.setVisible(true);
        pan_tampilkanBarang.setVisible(false);
        Kode_Barang.setText("");
        Kode_Barang1.setText("");
        Kode_Barang2.setText("");
        Kode_Barang3.setText("");
        jLabel9.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pan_barangKeluar.setVisible(true);
        pan_barangMasuk.setVisible(false);
        pan_tampilkanBarang.setVisible(false);
        Kode_Barang4.setText("");
        Kode_Barang5.setText("");
        jLabel9.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        pan_barangKeluar.setVisible(false);
        pan_barangMasuk.setVisible(false);
        pan_tampilkanBarang.setVisible(true);
        jLabel9.setVisible(false);
        
        display();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Kode_BarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kode_BarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kode_BarangActionPerformed

    private void Kode_Barang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kode_Barang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kode_Barang1ActionPerformed

    private void Kode_Barang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kode_Barang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kode_Barang2ActionPerformed

    private void Kode_Barang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kode_Barang3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kode_Barang3ActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        Date tanggal = null;
        try {
            tanggal = new SimpleDateFormat("dd-MM-yyyy").parse(Kode_Barang2.getText());
        } catch (ParseException e) {
            e.printStackTrace();
        }
        if (Kode_Barang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Kode Barang Belum Diisi", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (Kode_Barang1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Nama Barang Belum Diisi", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (Kode_Barang2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Tanggal Masuk Belum Diisi", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (Kode_Barang3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Jumlah Barang Belum Diisi", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (tanggal == null) {
            JOptionPane.showMessageDialog(null, "Format Tanggal tidak sesuai dd-MM-yyyy", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Barang barangBaru = new Barang(Integer.parseInt(Kode_Barang.getText()), Kode_Barang1.getText(), tanggal, Integer.parseInt(Kode_Barang3.getText()));
            inv.insertBarang(barangBaru);
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            pan_barangKeluar.setVisible(false);
            pan_barangMasuk.setVisible(false);
            pan_tampilkanBarang.setVisible(true);
            jLabel9.setVisible(false);
            display();
        }
    }//GEN-LAST:event_btnokActionPerformed

    private void Kode_Barang4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kode_Barang4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kode_Barang4ActionPerformed

    private void Kode_Barang5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kode_Barang5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Kode_Barang5ActionPerformed

    private void btnok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnok1ActionPerformed
        if (Kode_Barang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Kode Barang Belum Diisi", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (Kode_Barang4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Jumlah Barang Belum Diisi", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Barang barangKeluar = inv.removeBarang(Integer.parseInt(Kode_Barang4.getText()), Integer.parseInt(Kode_Barang5.getText()));
            if (barangKeluar != null) {
                System.out.println("Barang keluar dari inventori: " + barangKeluar.getNamaBarang());
                JOptionPane.showMessageDialog(null, "Barang berhasil dikurangkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                pan_barangKeluar.setVisible(false);
                pan_barangMasuk.setVisible(false);
                pan_tampilkanBarang.setVisible(true);
                jLabel9.setVisible(false);
                display();
            }
        }
    }//GEN-LAST:event_btnok1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String keyword = jTextField1.getText().trim(); // Ambil string pencarian
        tabmode.setRowCount(0); // Kosongkan tabel terlebih dahulu

        if (keyword.isEmpty()) {
            display(); // Tampilkan semua barang jika tidak ada kata kunci
        } else {
            for (Barang barang : inv.getAllSortedBarang()) {
                if (barang.getNamaBarang().toLowerCase().contains(keyword.toLowerCase())) { // Cek apakah nama barang mengandung kata kunci (case-insensitive)
                    Object[] row = new Object[4];
                    row[0] = barang.getIdBarang();
                    row[1] = barang.getNamaBarang();
                    row[2] = barang.getTanggalMasuk();
                    row[3] = barang.getJumlahBarang();
                    tabmode.addRow(row);
                }
            }
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Kode_Barang;
    private javax.swing.JTextField Kode_Barang1;
    private javax.swing.JTextField Kode_Barang2;
    private javax.swing.JTextField Kode_Barang3;
    private javax.swing.JTextField Kode_Barang4;
    private javax.swing.JTextField Kode_Barang5;
    private javax.swing.JButton btnok;
    private javax.swing.JButton btnok1;
    private javax.swing.JLabel isikm;
    private javax.swing.JLabel isikm1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pan_barangKeluar;
    private javax.swing.JPanel pan_barangMasuk;
    private javax.swing.JPanel pan_tampilkanBarang;
    // End of variables declaration//GEN-END:variables
}
